const jackets = [
  {
    name: "Active basic blue",
    sex: "men",
    fit: "Short jacket",
    price: 40,
    sizes: ["s", "m", "l", "xl", "xxl"],
    image: "/images/homepage/blue-small.jpg",
    description: "Our bestseller basic jacket is wind-and rainproof with a 5,00mm water resistance, and has inside-and outside pockets.",
    materials: "40% organic cotton, 60% recycled polyester",
    details: "White zipper, Article number 156-2344",
    homepage: true,
    id: 1,
  },
  {
    name: "Active basic yellow",
    sex: "women",
    fit: "Long jacket",
    price: 49,
    sizes: ["s", "m", "l", "xl", "xxl"],
    image: "/images/products/yellow-small3.jpg",
    description: "Our bestseller basic jacket, wind-and rainproof with a 5,00mm water resistance, and with inside-and outside pockets.",
    materials: "40% organic cotton, 60% recycled polyester",
    details: "White zipper, Article number 258-2344",
    homepage: false,
    id: 2,
  },
  {
    name: "Active basic orange",
    sex: "women",
    fit: "Long jacket",
    price: 40,
    sizes: ["s", "m", "l", "xl", "xxl"],
    image: "/images/products/orange-small2.jpg",
    description: "Our bestseller basic jacket, wind-and rainproof with a 5,00mm water resistance, with inside-and outside pockets.",
    materials: "40% organic cotton, 60% recycled polyester",
    details: "Invisible zipper, Article number 186-2774",
    homepage: false,
    id: 3,
  },
  {
    name: "Long coat blue",
    sex: "men",
    fit: "Long coat",
    price: 49,
    sizes: ["s", "m", "l", "xl", "xxl"],
    image: "/images/homepage/blue-small.jpg",
    description: "Long coated and durable rain jacket, wind-and rainproof with a 5,00mm water resistance.",
    materials: "44% organic cotton, 56% recycled polyester",
    details: "Invisible zipper, Article number 386-2300",
    homepage: true,
    id: 4,
  },
  {
    name: "Long coat orange",
    sex: "women",
    fit: "Long coat",
    price: 49,
    sizes: ["s", "m", "l", "xl", "xxl"],
    image: "/images/products/orange-small.jpg",
    description: "Long coated and durable rain jacket, wind-and rainproof with a 5,00mm water resistance.",
    materials: "44% organic cotton, 56% recycled polyester",
    details: "Invisible zipper, Article number 000-7894",
    homepage: false,
    id: 5,
  },
  {
    name: "Long coat yellow",
    sex: "women",
    fit: "Long coat",
    price: 49,
    sizes: ["s", "m", "l", "xl", "xxl"],
    image: "/images/products/yellow-small.jpg",
    description: "Long coated and durable rain jacket, wind-and rainproof with a 5,00mm water resistance.",
    materials: "44% organic cotton, 56% recycled polyester",
    details: "Black zipper, Article number 198-0994",
    homepage: false,
    id: 6,
  },
  {
    name: "Explorer",
    sex: "women",
    fit: "Short jacket",
    price: 40,
    sizes: ["s", "m", "l", "xl", "xxl"],
    image: "/images/products/red-small1.jpg",
    description: "Rain jacket with 10,000mm water resistance, suitable for all weather conditions and extremely durable.",
    materials: "48% organic cotton, 52% recycled polyester",
    details: "Invisible zipper, Article number 783-0143",
    homepage: false,
    id: 7,
  },
  {
    name: "Adventurer",
    sex: "women",
    fit: "Long jacket",
    price: 46,
    sizes: ["s", "m", "l", "xl", "xxl"],
    image: "/images/products/yellow-small.jpg",
    description: "Rain jacket with 10,000mm water resistance, suitable for all weather conditions and extremely durable.",
    materials: "46% organic cotton, 54% recycled polyester",
    details: "Invisible zipper, Article number 188-0152",
    homepage: true,
    id: 8,
  },
];
