const products = [
  {
    name: "Active basic blue",
    price: 40,
    image: "/images/homepage/blue-small.jpg",
    description: "Our bestseller basic jacket is wind-and rainproof with a 5,00mm water resistance, and has inside-and outside pockets.",
    materials: "Organic cotton and recycled polyester",
    homepage: true,
    id: 1,
  },
  {
    name: "Active basic yellow",
    price: 49,
    image: "/images/products/yellow-small3.jpg",
    description: "Our bestseller basic jacket, wind-and rainproof with a 5,00mm water resistance, and with inside-and outside pockets.",
    materials: "Organic cotton and recycled polyester",
    homepage: false,
    id: 2,
  },
  {
    name: "Active basic orange",
    price: 40,
    image: "/images/products/orange-small2.jpg",
    description: "Our bestseller basic jacket, wind-and rainproof with a 5,00mm water resistance, with inside-and outside pockets.",
    materials: "Organic cotton and recycled polyester",
    homepage: false,
    id: 3,
  },
  {
    name: "Long coat blue",
    price: 49,
    image: "/images/homepage/blue-small.jpg",
    description: "Long coated and durable rain jacket, wind-and rainproof with a 5,00mm water resistance.",
    materials: "Organic cotton and recycled polyester",
    homepage: true,
    id: 4,
  },
  {
    name: "Long coat orange",
    price: 49,
    image: "/images/products/orange-small.jpg",
    description: "Long coated and durable rain jacket, wind-and rainproof with a 5,00mm water resistance.",
    materials: "Organic cotton and recycled polyester",
    homepage: false,
    id: 5,
  },
  {
    name: "Long coat yellow",
    price: 49,
    image: "/images/products/yellow-small",
    description: "Long coated and durable rain jacket, wind-and rainproof with a 5,00mm water resistance.",
    materials: "Organic cotton and recycled polyester",
    homepage: false,
    id: 6,
  },
  {
    name: "Explorer",
    price: 40,
    image: "/images/products/red-small1.jpg",
    description: "Rain jacket with 10,000mm water resistance, suitable for all weather conditions and extremely durable.",
    materials: "Organic cotton and recycled polyester",
    homepage: false,
    id: 7,
  },
  {
    name: "Adventurer",
    price: 46,
    image: "/images/products/yellow-small.jpg",
    description: "Rain jacket with 10,000mm water resistance, suitable for all weather conditions and extremely durable.",
    materials: "Organic cotton and recycled polyester",
    homepage: true,
    id: 8,
  },
];
